### ISSUE TITLE
Descrever o Estudo de Caso (item 2)

### ISSUE THREAD

**Issue by danielfidelis** [alaorneto/bimaster_bi#4]
Realizar a descrição do item 2.1 do template do trabalho: contextualizar o caso nos primeiros parágrafos, apresentar os problemas, o foco do negócio e expectativas do cliente na metade do texto, e concluir indicando o objetivo final do projeto.

**Comment by danielfidelis** [comment]
Pessoal, @alaorneto @maiconmelo @lcvicente proponho realizarmos uma reunião para debater o mais breve possível esse item. Após sua definição poderemos desenvolver as outras atividades do trabalho.

**Comment by maiconmelo** [comment]
- Descrição do cartão. O que é, pra que serve, em que são usados. 
- Motivação: controle da sociedade sobre o gastos a fim de obter um uso eficiente dos recursos e combate a corrupção
- O projeto tratará o gasto ou compra como fato ativo a ser estudado...
- É desejável que seja possível obter relatórios como: grupo de serviço mais demandado, maiores demandantes, maiores favorecidos, evolução dos gastos durante anos eleitorais, meses com maiores gastos etc. 
- Ao final do projeto a empresa...

**Comment by maiconmelo** [comment]
Sugestão do Fidelis: http://www.portaltransparencia.gov.br/pagina-interna/603242-cartao-de-pagamento-do-governo-federal

**Comment by alaorneto** [comment]
Issue concluída com o commit 6ec91483ed0e9af1b08b06141d049ef6ed0d5ce8. Favor realizarem uma revisão do texto.
