### ISSUE TITLE
Descrever o modelo transacional (item 3)

### ISSUE THREAD

**Issue by maiconmelo** [alaorneto/bimaster_bi#5]
Submeti uma sugestão de DER para este problema. Está na pasta "documentos"

**Comment by lcvicente** [comment]
Modelo no arquivo **documentos\modelo_transacional.architect**. Descrição no arquivo **documentos\Descrição do Modelo Transacional.docx**

Algumas observações enquanto modelei:
- A relação entre órgao e órgão superior foi feita em auto-relacionamento. Desta forma, ficou uma tabela só para cadastrar os órgãos e nesta mesma identifica-se qual é o órgão superior e evita-se redundância (ex: Presidencia da República existe tanto em órgão quanto em órgão superior)

- Na tabela tipo_transação é possível identificar se o gasto foi feito em território nacional ou não. Observei alguns valores como "SAQUE - INT$ - APRES" e "COMPRA A/V - INT$ - APRES". Seria mais uma informação interessante para levarmos para o DW.

- Em alguns gastos, o favorecido foi pessoa física. Desta forma, teremos 2 "problemas":
1 - Identificar a natureza da atividade, como está sendo feito para o CNPJ, o que creio não ser possível.
2 - No caso da opção acima ser possível, podemos ter um mesmo CPF em mais de uma atividade. Isso mudaria o modelo.

Sugiro não detalharmos muito este ponto e assumir que todo favorecido pessoa física possui uma só natureza (Ex.: natureza = "PESSOA FISICA").

De qualquer forma é mais uma informação legal para o DW. Contabilizar gastos com pessoa física.

Podemos ajustar o modelo transacional de acordo com o que vamos precisar analisar no DW, retirando objetos ou resumindo o modelo se necessário.

**Comment by lcvicente** [comment]
Modelo transacional e descrição realizadas.
